ALTER TABLE `channel` DROP CONSTRAINT `FK_90e59c37a44fb796e67ef814b6f`;
ALTER TABLE `channel` ADD FOREIGN KEY (groupId) REFERENCES `group`(id) ON DELETE CASCADE;

ALTER TABLE `group_has_user` DROP CONSTRAINT `FK_7d0d66f93e53434d440ba53dca0`;
ALTER TABLE `group_has_user` DROP CONSTRAINT `FK_b06bffda5a627aff0e7d528c785`;
ALTER TABLE `group_has_user` ADD FOREIGN KEY (userId) REFERENCES `user`(id) ON DELETE CASCADE;
ALTER TABLE `group_has_user` ADD FOREIGN KEY (groupId) REFERENCES `group`(id) ON DELETE CASCADE;

